---
- name: copy hostfile to remotes
  copy:
    src: hostfile.txt
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
    backup: yes
  tags: gen_hostfile

- name: stop iptables
  service: name=iptables state=stopped
  ignore_errors: yes

- name: disbale on iptable on boot
  service: name=iptables enabled=no
  ignore_errors: yes

- name: remove root block
  command: sudo sed -i 's/.* ssh/ssh/'  /root/.ssh/authorized_keys
  tags: remove_root_keys
...
