---
default_java: jdk8
download_url: http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.tar.gz
download_folder: /opt

java_archive: "{{download_folder}}/jdk-8u131-linux-x64.tar.gz"
java_name: "{{download_folder}}/jdk1.8.0_131"
JAVA_HOME: "/opt/jdk1.8.0_131"

users:
  hadoop_users:
    - test

hadoop_src_url: http://apache.mesi.com.ar/hadoop/common/hadoop-2.8.0/hadoop-2.8.0.tar.gz
hadoop_archive: "{{download_folder}}/hadoop-2.8.0.tar.gz"
hadoop_name: "{{download_folder}}/hadoop-2.8.0"

ambari:
  repo_url: http://public-repo-1.hortonworks.com/ambari/centos7/2.x/updates/2.4.1.0/ambari.repo

distcp_pairs:
  cluster_a:
    cluster_name: node0
    nn1: ip-10-0-2-216.eu-west-1.compute.internal
  cluster_b:
    cluster_name: node1
    nn1: ip-10-0-3-158.eu-west-1.compute.internal
...
