---
- hosts: localhost
  tasks:


    - name: take out of load balancer pool
      command: ./gen_hostfile.py > hostfile.txt
      args:
          chdir: "{{ role_path }}/files"
      delegate_to: 127.0.0.1
      run_once: true
      tags: gen_hostfile
...
